/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

export interface GetHooksQuery {
  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

}

export interface UnnamedModel {
  url?: string

  content_type?: string

  insecure_ssl?: string

  secret?: string

}

export interface Global_hook {
  type?: string

  id?: number

  name?: string

  active?: boolean

  events?: string[]

  config?: UnnamedModel

  updated_at?: string

  created_at?: string

  url?: string

  ping_url?: string

}

/**
 * Key/value pairs to provide settings for this webhook.
 */
export interface UnnamedModel$1 {
  /**
   * The URL to which the payloads will be delivered.
   */
  url?: string

  /**
   * The media type used to serialize the payloads. Supported values include `json` and `form`. The default is `form`.
   */
  content_type?: string

  /**
   * If provided, the `secret` will be used as the `key` to generate the HMAC hex digest value in the [`X-Hub-Signature`](https://docs.github.com/enterprise-server@3.0/webhooks/event-payloads/#delivery-headers) header.
   */
  secret?: string

  /**
   * Determines whether the SSL certificate of the host for `url` will be verified when delivering payloads. Supported values include `0` (verification is performed) and `1` (verification is not performed). The default is `0`. **We strongly recommend not setting this to `1` as you are subject to man-in-the-middle and other attacks.**
   */
  insecure_ssl?: string

}

export interface UnnamedModel$2 {
  /**
   * Must be passed as "web".
   */
  name?: string

  /**
   * Key/value pairs to provide settings for this webhook.
   */
  config?: UnnamedModel$1

  events?: string[]

  /**
   * Determines if notifications are sent when the webhook is triggered. Set to `true` to send notifications.
   */
  active?: boolean

}

/**
 * Key/value pairs to provide settings for this webhook.
 */
export interface UnnamedModel$3 {
  /**
   * The URL to which the payloads will be delivered.
   */
  url?: string

  /**
   * The media type used to serialize the payloads. Supported values include `json` and `form`. The default is `form`.
   */
  content_type?: string

  /**
   * If provided, the `secret` will be used as the `key` to generate the HMAC hex digest value in the [`X-Hub-Signature`](https://docs.github.com/enterprise-server@3.0/webhooks/event-payloads/#delivery-headers) header.
   */
  secret?: string

  /**
   * Determines whether the SSL certificate of the host for `url` will be verified when delivering payloads. Supported values include `0` (verification is performed) and `1` (verification is not performed). The default is `0`. **We strongly recommend not setting this to `1` as you are subject to man-in-the-middle and other attacks.**
   */
  insecure_ssl?: string

}

export interface UnnamedModel$4 {
  /**
   * Key/value pairs to provide settings for this webhook.
   */
  config?: UnnamedModel$3

  events?: string[]

  /**
   * Determines if notifications are sent when the webhook is triggered. Set to `true` to send notifications.
   */
  active?: boolean

}

export interface UnnamedModel$5 {
  url?: string

  content_type?: string

  insecure_ssl?: string

}

export interface Global_hook_2 {
  type?: string

  id?: number

  name?: string

  active?: boolean

  events?: string[]

  config?: UnnamedModel$5

  updated_at?: string

  created_at?: string

  url?: string

  ping_url?: string

}

export interface GetKeysQuery {
  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

  /**
   * One of `asc` (ascending) or `desc` (descending).
   */
  direction?: string

  sort?: string

  /**
   * Only show public keys accessed after the given time.
   */
  since?: string

}

export interface Public_key_full {
  id?: number

  key?: string

  user_id?: number | null

  repository_id?: number | null

  url?: string

  title?: string

  read_only?: boolean

  verified?: boolean

  created_at?: string

  last_used?: string | null

}

export interface UnnamedModel$6 {
  /**
   * The [distinguished name](https://www.ldap.com/ldap-dns-and-rdns) (DN) of the LDAP entry to map to a team.
   */
  ldap_dn?: string

}

export interface Ldap_mapping_team {
  ldap_dn?: string

  id?: number

  node_id?: string

  url?: string

  html_url?: string

  name?: string

  slug?: string

  description?: string | null

  privacy?: string

  permission?: string

  members_url?: string

  repositories_url?: string

  parent?: null

}

export interface UnnamedModel$7 {
  /**
   * The [distinguished name](https://www.ldap.com/ldap-dns-and-rdns) (DN) of the LDAP entry to map to a team.
   */
  ldap_dn?: string

}

export interface UnnamedModel$8 {
  collaborators?: number

  name?: string

  space?: number

  private_repos?: number

}

/**
 * Ldap Private User
 */
export interface Ldap_mapping_user {
  ldap_dn?: string

  login?: string

  id?: number

  node_id?: string

  avatar_url?: string

  gravatar_id?: string | null

  url?: string

  html_url?: string

  followers_url?: string

  following_url?: string

  gists_url?: string

  starred_url?: string

  subscriptions_url?: string

  organizations_url?: string

  repos_url?: string

  events_url?: string

  received_events_url?: string

  type?: string

  site_admin?: boolean

  name?: string | null

  company?: string | null

  blog?: string | null

  location?: string | null

  email?: string | null

  hireable?: boolean | null

  bio?: string | null

  twitter_username?: string | null

  public_repos?: number

  public_gists?: number

  followers?: number

  following?: number

  created_at?: string

  updated_at?: string

  private_gists?: number

  total_private_repos?: number

  owned_private_repos?: number

  disk_usage?: number

  collaborators?: number

  two_factor_authentication?: boolean

  plan?: UnnamedModel$8

  suspended_at?: string

  business_plus?: boolean

}

export interface UnnamedModel$9 {
  /**
   * The organization's username.
   */
  login?: string

  /**
   * The login of the user who will manage this organization.
   */
  admin?: string

  /**
   * The organization's display name.
   */
  profile_name?: string

}

export interface UnnamedModel$10 {
  /**
   * The organization's new name.
   */
  login?: string

}

export interface GetPreReceiveEnvironmentsQuery {
  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

  /**
   * One of `asc` (ascending) or `desc` (descending).
   */
  direction?: string

  sort?: string

}

export interface UnnamedModel$11 {
  url?: string

  state?: string

  downloaded_at?: string | null

  message?: string | null

}

export interface Pre_receive_environment {
  id?: number

  name?: string

  image_url?: string

  url?: string

  html_url?: string

  default_environment?: boolean

  created_at?: string

  hooks_count?: number

  download?: UnnamedModel$11

}

export interface UnnamedModel$12 {
  /**
   * The new pre-receive environment's name.
   */
  name?: string

  /**
   * URL from which to download a tarball of this environment.
   */
  image_url?: string

}

export interface UnnamedModel$13 {
  /**
   * This pre-receive environment's new name.
   */
  name?: string

  /**
   * URL from which to download a tarball of this environment.
   */
  image_url?: string

}

export interface Pre_receive_environment_download_status {
  url?: string

  state?: string

  downloaded_at?: string | null

  message?: string | null

}

export interface GetPreReceiveHooksQuery {
  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

  /**
   * One of `asc` (ascending) or `desc` (descending).
   */
  direction?: string

  /**
   * One of `created` (when the repository was starred) or `updated` (when it was last pushed to) or `name`.
   */
  sort?: string

}

export interface UnnamedModel$14 {
  id?: number

  full_name?: string

  url?: string

  html_url?: string

}

export interface UnnamedModel$15 {
  url?: string

  state?: string

  downloaded_at?: string | null

  message?: string | null

}

export interface UnnamedModel$16 {
  id?: number

  name?: string

  image_url?: string

  url?: string

  html_url?: string

  default_environment?: boolean

  created_at?: string

  hooks_count?: number

  download?: UnnamedModel$15

}

export interface Pre_receive_hook {
  id?: number

  name?: string

  enforcement?: string

  script?: string

  script_repository?: UnnamedModel$14

  environment?: UnnamedModel$16

  allow_downstream_configuration?: boolean

}

export interface UnnamedModel$17 {
  /**
   * The name of the hook.
   */
  name?: string

  /**
   * The script that the hook runs.
   */
  script?: string

  /**
   * The GitHub repository where the script is kept.
   */
  script_repository?: Record<string, any>

  /**
   * The pre-receive environment where the script is executed.
   */
  environment?: Record<string, any>

  /**
   * The state of enforcement for this hook. default: `disabled`
   */
  enforcement?: string

  /**
   * Whether enforcement can be overridden at the org or repo level. default: `false`
   */
  allow_downstream_configuration?: boolean

}

export interface UnnamedModel$18 {
  /**
   * The name of the hook.
   */
  name?: string

  /**
   * The script that the hook runs.
   */
  script?: string

  /**
   * The GitHub repository where the script is kept.
   */
  script_repository?: Record<string, any>

  /**
   * The pre-receive environment where the script is executed.
   */
  environment?: Record<string, any>

  /**
   * The state of enforcement for this hook.
   */
  enforcement?: string

  /**
   * Whether enforcement can be overridden at the org or repo level.
   */
  allow_downstream_configuration?: boolean

}

export interface GetTokensQuery {
  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

}

export interface UnnamedModel$19 {
  client_id?: string

  name?: string

  url?: string

}

/**
 * The authorization for an OAuth app, GitHub App, or a Personal Access Token.
 */
export interface Authorization {
  id?: number

  url?: string

  /**
   * A list of scopes that this authorization is in.
   */
  scopes?: any[] | null

  token?: string

  token_last_eight?: string | null

  hashed_token?: string | null

  app?: UnnamedModel$19

  note?: string | null

  note_url?: string | null

  updated_at?: string

  created_at?: string

  fingerprint?: string | null

  user?: any

  installation?: any

}

export interface UnnamedModel$20 {
  /**
   * The user's username.
   */
  login?: string

  /**
   * **Required for built-in authentication.** The user's email address. This parameter can be omitted when using CAS, LDAP, or SAML. For details on built-in and centrally-managed authentication, see the the [GitHub authentication guide](https://docs.github.com/enterprise/2.18/admin/guides/user-management/authenticating-users-for-your-github-enterprise-server-instance/).
   */
  email?: string

}

export interface UnnamedModel$21 {
  /**
   * The user's new username.
   */
  login?: string

}

export interface UnnamedModel$22 {
  scopes?: string[]

}
