/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

export interface GetGrantsQuery {
  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

  /**
   * The client ID of your GitHub app.
   */
  clientid?: string

}

export interface UnnamedModel {
  client_id?: string

  name?: string

  url?: string

}

/**
 * The authorization associated with an OAuth Access.
 */
export interface Application_grant {
  id?: number

  url?: string

  app?: UnnamedModel

  created_at?: string

  updated_at?: string

  scopes?: string[]

  user?: any

}

export interface UnnamedModel$1 {
  /**
   * The OAuth access token used to authenticate to the GitHub API.
   */
  access_token?: string

}

export interface UnnamedModel$2 {
  /**
   * The access_token of the OAuth application.
   */
  access_token?: string

}

export interface UnnamedModel$3 {
  /**
   * The access_token of the OAuth application.
   */
  access_token?: string

}

export interface UnnamedModel$4 {
  /**
   * The OAuth access token used to authenticate to the GitHub API.
   */
  access_token?: string

}

export interface UnnamedModel$5 {
  /**
   * The OAuth access token used to authenticate to the GitHub API.
   */
  access_token?: string

  /**
   * The name of the user or organization to scope the user-to-server access token to. **Required** unless `target_id` is specified.
   */
  target?: string

  /**
   * The ID of the user or organization to scope the user-to-server access token to. **Required** unless `target` is specified.
   */
  target_id?: number

  repositories?: string[]

  repository_ids?: number[]

  permissions?: any

}
