/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */

export interface GetQuery {
  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

  /**
   * The client ID of your GitHub app.
   */
  clientid?: string

}

export interface UnnamedModel {
  /**
   * A list of scopes that this authorization is in.
   */
  scopes?: any[] | null

  /**
   * A note to remind you what the OAuth token is for.
   */
  note?: string

  /**
   * A URL to remind you what app the OAuth token is for.
   */
  note_url?: string

  /**
   * The OAuth app client key for which to create the token.
   */
  client_id?: string

  /**
   * The OAuth app client secret for which to create the token.
   */
  client_secret?: string

  /**
   * A unique string to distinguish an authorization from others created for the same client ID and user.
   */
  fingerprint?: string

}

export interface UnnamedModel$1 {
  /**
   * The OAuth app client secret for which to create the token.
   */
  client_secret?: string

  /**
   * A list of scopes that this authorization is in.
   */
  scopes?: any[] | null

  /**
   * A note to remind you what the OAuth token is for.
   */
  note?: string

  /**
   * A URL to remind you what app the OAuth token is for.
   */
  note_url?: string

  /**
   * A unique string to distinguish an authorization from others created for the same client ID and user.
   */
  fingerprint?: string

}

export interface UnnamedModel$2 {
  /**
   * The OAuth app client secret for which to create the token.
   */
  client_secret?: string

  /**
   * A list of scopes that this authorization is in.
   */
  scopes?: any[] | null

  /**
   * A note to remind you what the OAuth token is for.
   */
  note?: string

  /**
   * A URL to remind you what app the OAuth token is for.
   */
  note_url?: string

}

export interface UnnamedModel$3 {
  /**
   * A list of scopes that this authorization is in.
   */
  scopes?: any[] | null

  add_scopes?: string[]

  remove_scopes?: string[]

  /**
   * A note to remind you what the OAuth token is for.
   */
  note?: string

  /**
   * A URL to remind you what app the OAuth token is for.
   */
  note_url?: string

  /**
   * A unique string to distinguish an authorization from others created for the same client ID and user.
   */
  fingerprint?: string

}
