/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

/**
 * Code Of Conduct
 */
export interface Code_of_conduct {
  key?: string

  name?: string

  url?: string

  body?: string

  html_url?: string | null

}
