/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

/**
 * Enterprise global announcement
 */
export interface Announcement {
  /**
   * The announcement text in GitHub Flavored Markdown. For more information about GitHub Flavored Markdown, see "[Basic writing and formatting syntax](https://docs.github.com/enterprise-server@3.0/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)."
   */
  announcement?: string

  /**
   * The time at which the announcement expires. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`. To set an announcement that never expires, omit this parameter, set it to `null`, or set it to an empty string.
   */
  expires_at?: string | null

}

export interface License_info {
  seats?: any

  seats_used?: number

  seats_available?: any

  kind?: string

  days_until_expiration?: number

  expire_at?: string

}

export interface Enterprise_repository_overview {
  total_repos?: number

  root_repos?: number

  fork_repos?: number

  org_repos?: number

  total_pushes?: number

  total_wikis?: number

}

export interface Enterprise_hook_overview {
  total_hooks?: number

  active_hooks?: number

  inactive_hooks?: number

}

export interface Enterprise_page_overview {
  total_pages?: number

}

export interface Enterprise_organization_overview {
  total_orgs?: number

  disabled_orgs?: number

  total_teams?: number

  total_team_members?: number

}

export interface Enterprise_user_overview {
  total_users?: number

  admin_users?: number

  suspended_users?: number

}

export interface Enterprise_pull_request_overview {
  total_pulls?: number

  merged_pulls?: number

  mergeable_pulls?: number

  unmergeable_pulls?: number

}

export interface Enterprise_issue_overview {
  total_issues?: number

  open_issues?: number

  closed_issues?: number

}

export interface Enterprise_milestone_overview {
  total_milestones?: number

  open_milestones?: number

  closed_milestones?: number

}

export interface Enterprise_gist_overview {
  total_gists?: number

  private_gists?: number

  public_gists?: number

}

export interface Enterprise_comment_overview {
  total_commit_comments?: number

  total_gist_comments?: number

  total_issue_comments?: number

  total_pull_request_comments?: number

}

export interface Enterprise_overview {
  repos?: Enterprise_repository_overview

  hooks?: Enterprise_hook_overview

  pages?: Enterprise_page_overview

  orgs?: Enterprise_organization_overview

  users?: Enterprise_user_overview

  pulls?: Enterprise_pull_request_overview

  issues?: Enterprise_issue_overview

  milestones?: Enterprise_milestone_overview

  gists?: Enterprise_gist_overview

  comments?: Enterprise_comment_overview

}
