/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

export interface GetQuery {
  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

}

/**
 * Actor
 */
export interface Actor {
  id?: number

  login?: string

  display_login?: string

  gravatar_id?: string | null

  url?: string

  avatar_url?: string

}

export interface UnnamedModel {
  id?: number

  name?: string

  url?: string

}

export interface UnnamedModel$1 {
  merged_at?: string | null

  diff_url?: string | null

  html_url?: string | null

  patch_url?: string | null

  url?: string | null

}

export interface UnnamedModel$2 {
  admin?: boolean

  pull?: boolean

  triage?: boolean

  push?: boolean

  maintain?: boolean

}

/**
 * Simple User
 */
export interface Simple_user {
  name?: string | null

  email?: string | null

  login?: string

  id?: number

  node_id?: string

  avatar_url?: string

  gravatar_id?: string | null

  url?: string

  html_url?: string

  followers_url?: string

  following_url?: string

  gists_url?: string

  starred_url?: string

  subscriptions_url?: string

  organizations_url?: string

  repos_url?: string

  events_url?: string

  received_events_url?: string

  type?: string

  site_admin?: boolean

  starred_at?: string

}

/**
 * A git repository
 */
export interface Repository {
  /**
   * Unique identifier of the repository
   */
  id?: number

  node_id?: string

  /**
   * The name of the repository.
   */
  name?: string

  full_name?: string

  license?: any

  organization?: any

  forks?: number

  permissions?: UnnamedModel$2

  /**
   * Simple User
   */
  owner?: Simple_user

  /**
   * Whether the repository is private or public.
   */
  private?: boolean

  html_url?: string

  description?: string | null

  fork?: boolean

  url?: string

  archive_url?: string

  assignees_url?: string

  blobs_url?: string

  branches_url?: string

  collaborators_url?: string

  comments_url?: string

  commits_url?: string

  compare_url?: string

  contents_url?: string

  contributors_url?: string

  deployments_url?: string

  downloads_url?: string

  events_url?: string

  forks_url?: string

  git_commits_url?: string

  git_refs_url?: string

  git_tags_url?: string

  git_url?: string

  issue_comment_url?: string

  issue_events_url?: string

  issues_url?: string

  keys_url?: string

  labels_url?: string

  languages_url?: string

  merges_url?: string

  milestones_url?: string

  notifications_url?: string

  pulls_url?: string

  releases_url?: string

  ssh_url?: string

  stargazers_url?: string

  statuses_url?: string

  subscribers_url?: string

  subscription_url?: string

  tags_url?: string

  teams_url?: string

  trees_url?: string

  clone_url?: string

  mirror_url?: string | null

  hooks_url?: string

  svn_url?: string

  homepage?: string | null

  language?: string | null

  forks_count?: number

  stargazers_count?: number

  watchers_count?: number

  size?: number

  /**
   * The default branch of the repository.
   */
  default_branch?: string

  open_issues_count?: number

  /**
   * Whether this repository acts as a template that can be used to generate new repositories.
   */
  is_template?: boolean

  topics?: string[]

  /**
   * Whether issues are enabled.
   */
  has_issues?: boolean

  /**
   * Whether projects are enabled.
   */
  has_projects?: boolean

  /**
   * Whether the wiki is enabled.
   */
  has_wiki?: boolean

  has_pages?: boolean

  /**
   * Whether downloads are enabled.
   */
  has_downloads?: boolean

  /**
   * Whether the repository is archived.
   */
  archived?: boolean

  /**
   * Returns whether or not this repository disabled.
   */
  disabled?: boolean

  /**
   * The repository visibility: public, private, or internal.
   */
  visibility?: string

  pushed_at?: string | null

  created_at?: string | null

  updated_at?: string | null

  /**
   * Whether to allow rebase merges for pull requests.
   */
  allow_rebase_merge?: boolean

  template_repository?: any | null

  temp_clone_token?: string

  /**
   * Whether to allow squash merges for pull requests.
   */
  allow_squash_merge?: boolean

  /**
   * Whether to delete head branches when pull requests are merged
   */
  delete_branch_on_merge?: boolean

  /**
   * Whether to allow merge commits for pull requests.
   */
  allow_merge_commit?: boolean

  /**
   * Whether to allow forking this repo
   */
  allow_forking?: boolean

  subscribers_count?: number

  network_count?: number

  open_issues?: number

  watchers?: number

  master_branch?: string

  starred_at?: string

}

export interface Reaction_rollup {
  url?: string

  total_count?: number

  +1?: number

  -1?: number

  laugh?: number

  confused?: number

  heart?: number

  hooray?: number

  eyes?: number

  rocket?: number

}

/**
 * Issues are a great way to keep track of tasks, enhancements, and bugs for your projects.
 */
export interface Issue {
  id?: number

  node_id?: string

  /**
   * URL for the issue
   */
  url?: string

  repository_url?: string

  labels_url?: string

  comments_url?: string

  events_url?: string

  html_url?: string

  /**
   * Number uniquely identifying the issue within its repository
   */
  number?: number

  /**
   * State of the issue; either 'open' or 'closed'
   */
  state?: string

  /**
   * Title of the issue
   */
  title?: string

  /**
   * Contents of the issue
   */
  body?: string | null

  user?: any

  labels?: any[]

  assignee?: any

  assignees?: any[] | null

  milestone?: any

  locked?: boolean

  active_lock_reason?: string | null

  comments?: number

  pull_request?: UnnamedModel$1

  closed_at?: string | null

  created_at?: string

  updated_at?: string

  draft?: boolean

  closed_by?: any

  body_html?: string

  body_text?: string

  timeline_url?: string

  /**
   * A git repository
   */
  repository?: Repository

  performed_via_github_app?: any

  /**
   * How the author is associated with the repository.
   */
  author_association?: string

  reactions?: Reaction_rollup

}

/**
 * Comments provide a way for people to collaborate on an issue.
 */
export interface Issue_comment {
  /**
   * Unique identifier of the issue comment
   */
  id?: number

  node_id?: string

  /**
   * URL for the issue comment
   */
  url?: string

  /**
   * Contents of the issue comment
   */
  body?: string

  body_text?: string

  body_html?: string

  html_url?: string

  user?: any

  created_at?: string

  updated_at?: string

  issue_url?: string

  author_association?: any

  performed_via_github_app?: any

  reactions?: any

}

export interface UnnamedModel$3 {
  page_name?: string

  title?: string

  summary?: string | null

  action?: string

  sha?: string

  html_url?: string

}

export interface UnnamedModel$4 {
  action?: string

  /**
   * Issues are a great way to keep track of tasks, enhancements, and bugs for your projects.
   */
  issue?: Issue

  /**
   * Comments provide a way for people to collaborate on an issue.
   */
  comment?: Issue_comment

  pages?: UnnamedModel$3[]

}

/**
 * Event
 */
export interface Event {
  id?: string

  type?: string | null

  /**
   * Actor
   */
  actor?: Actor

  repo?: UnnamedModel

  org?: any

  payload?: UnnamedModel$4

  public?: boolean

  created_at?: string | null

}
