/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

/**
 * Hypermedia Link with Type
 */
export interface Link_with_type {
  href?: string

  type?: string

}

export interface UnnamedModel {
  /**
   * Hypermedia Link with Type
   */
  timeline?: Link_with_type

  user?: any

  security_advisories?: any

  current_user?: any

  current_user_public?: any

  current_user_actor?: any

  current_user_organization?: any

  current_user_organizations?: any[]

}

/**
 * Feed
 */
export interface Feed {
  timeline_url?: string

  user_url?: string

  current_user_public_url?: string

  current_user_url?: string

  current_user_actor_url?: string

  current_user_organization_url?: string

  current_user_organization_urls?: string[]

  _links?: UnnamedModel

}
