/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

/**
 * Gitignore Template
 */
export interface Gitignore_template {
  name?: string

  source?: string

}
