/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

export interface GetQuery {
  /**
   * Indicates which sorts of issues to return. Can be one of:  
\* `assigned`: Issues assigned to you  
\* `created`: Issues created by you  
\* `mentioned`: Issues mentioning you  
\* `subscribed`: Issues you're subscribed to updates for  
\* `all` or `repos`: All issues the authenticated user can see, regardless of participation or creation
   */
  filter?: string

  /**
   * Indicates the state of the issues to return. Can be either `open`, `closed`, or `all`.
   */
  state?: string

  /**
   * A list of comma separated label names. Example: `bug,ui,@high`
   */
  labels?: string

  /**
   * What to sort results by. Can be either `created`, `updated`, `comments`.
   */
  sort?: string

  /**
   * One of `asc` (ascending) or `desc` (descending).
   */
  direction?: string

  /**
   * Only show notifications updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.
   */
  since?: string

  collab?: boolean

  orgs?: boolean

  owned?: boolean

  pulls?: boolean

  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

}
