/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */

export interface GetQuery {
  featured?: boolean

  /**
   * Results per page (max 100)
   */
  perpage?: number

  /**
   * Page number of the results to fetch.
   */
  page?: number

}

/**
 * License Simple
 */
export interface License_simple {
  key?: string

  name?: string

  url?: string | null

  spdx_id?: string | null

  node_id?: string

  html_url?: string

}

/**
 * License
 */
export interface License {
  key?: string

  name?: string

  spdx_id?: string | null

  url?: string | null

  node_id?: string

  html_url?: string

  description?: string

  implementation?: string

  permissions?: string[]

  conditions?: string[]

  limitations?: string[]

  body?: string

  featured?: boolean

}
