/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

/**
 * Api Overview
 */
export interface Api_overview {
  verifiable_password_authentication?: boolean

  packages?: string[]

  dependabot?: string[]

  installed_version?: string

}
