/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

export interface GetQuery {
  /**
   * The words to show in Octocat's speech bubble
   */
  s?: string

}
