/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

export interface GetQuery {
  /**
   * An organization ID. Only return organizations with an ID greater than this ID.
   */
  since?: number

  /**
   * Results per page (max 100)
   */
  perpage?: number

}
