/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

export interface Rate_limit {
  limit?: number

  remaining?: number

  reset?: number

  used?: number

}

export interface UnnamedModel {
  core?: Rate_limit

  graphql?: any

  search?: any

  source_import?: any

  integration_manifest?: any

  code_scanning_upload?: any

  actions_runner_registration?: any

  scim?: any

}

/**
 * Rate Limit Overview
 */
export interface Rate_limit_overview {
  resources?: UnnamedModel

  rate?: any

}
