/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */

export interface UnnamedModel {
  status?: string

  key?: string

}

export interface Configuration_status {
  status?: string

  progress?: UnnamedModel[]

}

export interface UnnamedModel$1 {
  name?: string

  number?: number

}

export interface Maintenance_status {
  status?: string

  scheduled_time?: string

  connection_services?: UnnamedModel$1[]

}

export interface UnnamedModel$2 {
  enabled?: boolean

  uri?: string

}

export interface UnnamedModel$3 {
  name?: string

  email?: string

  uuid?: string

  secret_key_data?: string

  public_key_data?: string

}

export interface UnnamedModel$4 {
  seats?: number

  evaluation?: boolean

  perpetual?: boolean

  unlimited_seating?: boolean

  support_key?: string

  ssh_allowed?: boolean

  cluster_support?: boolean

  expire_at?: string

}

export interface UnnamedModel$5 {
  enabled?: boolean

  cert?: string | null

  key?: string | null

}

export interface UnnamedModel$6 {
  user?: string | null

  org?: string | null

}

export interface UnnamedModel$7 {
  uid?: string

  name?: string | null

  mail?: string | null

  key?: string | null

}

export interface UnnamedModel$8 {
  host?: string | null

  port?: number

  base?: any[]

  uid?: string | null

  bind_dn?: string | null

  password?: string | null

  method?: string

  search_strategy?: string

  user_groups?: any[]

  admin_group?: string | null

  virtual_attribute_enabled?: boolean

  recursive_group_search?: boolean

  posix_support?: boolean

  user_sync_emails?: boolean

  user_sync_keys?: boolean

  user_sync_interval?: number

  team_sync_interval?: number

  sync_enabled?: boolean

  reconciliation?: UnnamedModel$6

  profile?: UnnamedModel$7

}

export interface UnnamedModel$9 {
  url?: string | null

}

export interface UnnamedModel$10 {
  sso_url?: string | null

  certificate?: string | null

  certificate_path?: string | null

  issuer?: string | null

  idp_initiated_sso?: boolean

  disable_admin_demote?: boolean

}

export interface UnnamedModel$11 {
  client_id?: string

  client_secret?: string

  organization_name?: string

  organization_team?: string

}

export interface UnnamedModel$12 {
  enabled?: boolean

  address?: string

  authentication?: string

  port?: string

  domain?: string

  username?: string

  user_name?: string

  enable_starttls_auto?: boolean

  password?: string

  discard-to-noreply-address?: boolean

  support_address?: string

  support_address_type?: string

  noreply_address?: string

}

export interface UnnamedModel$13 {
  primary_server?: string

  secondary_server?: string

}

export interface UnnamedModel$14 {
  enabled?: boolean

  community?: string

}

export interface UnnamedModel$15 {
  enabled?: boolean

  server?: string | null

  protocol_name?: string

}

export interface UnnamedModel$16 {
  enabled?: boolean

}

export interface UnnamedModel$17 {
  enabled?: boolean

  server?: string | null

  port?: number

  encryption?: string | null

  username?: string | null

  password?: string | null

}

export interface UnnamedModel$18 {
  enabled?: boolean

  tileserver?: string | null

  basemap?: string

  token?: string | null

}

export interface UnnamedModel$19 {
  private_mode?: boolean

  public_pages?: boolean

  subdomain_isolation?: boolean

  signup_enabled?: boolean

  github_hostname?: string

  identicons_host?: string

  http_proxy?: string | null

  auth_mode?: string

  expire_sessions?: boolean

  admin_password?: string | null

  configuration_id?: number

  configuration_run_count?: number

  avatar?: UnnamedModel$2

  customer?: UnnamedModel$3

  license?: UnnamedModel$4

  github_ssl?: UnnamedModel$5

  ldap?: UnnamedModel$8

  cas?: UnnamedModel$9

  saml?: UnnamedModel$10

  github_oauth?: UnnamedModel$11

  smtp?: UnnamedModel$12

  ntp?: UnnamedModel$13

  timezone?: string | null

  snmp?: UnnamedModel$14

  syslog?: UnnamedModel$15

  assets?: string | null

  pages?: UnnamedModel$16

  collectd?: UnnamedModel$17

  mapping?: UnnamedModel$18

  load_balancer?: string | null

}

export interface Enterprise_settings {
  enterprise?: UnnamedModel$19

  run_list?: string[]

}

export interface Ssh_key {
  key?: string

  pretty-print?: string

}
