/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */

export interface UnnamedModel {
  current_user_url?: string

  current_user_authorizations_html_url?: string

  authorizations_url?: string

  code_search_url?: string

  commit_search_url?: string

  emails_url?: string

  emojis_url?: string

  events_url?: string

  feeds_url?: string

  followers_url?: string

  following_url?: string

  gists_url?: string

  hub_url?: string

  issue_search_url?: string

  issues_url?: string

  keys_url?: string

  label_search_url?: string

  notifications_url?: string

  organization_url?: string

  organization_repositories_url?: string

  organization_teams_url?: string

  public_gists_url?: string

  rate_limit_url?: string

  repository_url?: string

  repository_search_url?: string

  current_user_repositories_url?: string

  starred_url?: string

  starred_gists_url?: string

  topic_search_url?: string

  user_url?: string

  user_organizations_url?: string

  user_repositories_url?: string

  user_search_url?: string

}
