/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */
import { api, type Config, type Api } from 'autoapi'

/**
 * Create a GitHub App from a manifest
Use this endpoint to complete the handshake necessary when implementing the [GitHub App Manifest flow](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/creating-github-apps-from-a-manifest/). When you create a GitHub App with the manifest flow, you receive a temporary `code` used to retrieve the GitHub App's `id`, `pem` (private key), and `webhook_secret`.
 */
export const postByCodeConversions = api<(paths?: string, body?: Record<string, any>, config?: Config<any, Record<string, any>>) => any>`POST /app-manifests/{code}/conversions`

export type PostByCodeConversions = Api<typeof postByCodeConversions>
