/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */
import { api, type Config, type Api } from 'ts-autoapi'
import {
  UnnamedModel,
  Integration,
  Webhook_config,
  UnnamedModel$1,
  GetInstallationsQuery,
  Installation,
  UnnamedModel$2
} from './models/app.d'

/**
 * Get the authenticated app
Returns the GitHub App associated with the authentication credentials used. To see how many app installations are associated with this GitHub App, see the `installations_count` in the response. For more details about your app's installations, see the "[List installations for the authenticated app](https://docs.github.com/enterprise-server@3.0/rest/reference/apps#list-installations-for-the-authenticated-app)" endpoint.

You must use a [JWT](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 */
export const get = api<(config?: Config<any, any>) => Integration>`GET /app`

export type Get = Api<typeof get>

/**
 * Get a webhook configuration for an app
Returns the webhook configuration for a GitHub App. For more information about configuring a webhook for your app, see "[Creating a GitHub App](/developers/apps/creating-a-github-app)."

You must use a [JWT](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 */
export const getHookConfig = api<(config?: Config<any, any>) => Webhook_config>`GET /app/hook/config`

export type GetHookConfig = Api<typeof getHookConfig>

/**
 * Update a webhook configuration for an app
Updates the webhook configuration for a GitHub App. For more information about configuring a webhook for your app, see "[Creating a GitHub App](/developers/apps/creating-a-github-app)."

You must use a [JWT](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 */
export const patchHookConfig = api<(body?: UnnamedModel$1, config?: Config<any, UnnamedModel$1>) => any>`PATCH /app/hook/config`

export type PatchHookConfig = Api<typeof patchHookConfig>

/**
 * List installations for the authenticated app
You must use a [JWT](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.

The permissions the installation has are included under the `permissions` key.
 */
export const getInstallations = api<(query?: GetInstallationsQuery, config?: Config<GetInstallationsQuery, any>) => Installation[]>`GET /app/installations`

export type GetInstallations = Api<typeof getInstallations>

/**
 * Get an installation for the authenticated app
Enables an authenticated GitHub App to find an installation's information using the installation id.

You must use a [JWT](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 */
export const getInstallationsByInstallationId = api<(paths?: number, config?: Config<any, any>) => any>`GET /app/installations/{installation_id}`

export type GetInstallationsByInstallationId = Api<typeof getInstallationsByInstallationId>

/**
 * Delete an installation for the authenticated app
Uninstalls a GitHub App on a user, organization, or business account. If you prefer to temporarily suspend an app's access to your account's resources, then we recommend the "[Suspend an app installation](https://docs.github.com/enterprise-server@3.0/rest/reference/apps/#suspend-an-app-installation)" endpoint.

You must use a [JWT](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 */
export const deleteInstallationsByInstallationId = api<(paths?: number, config?: Config<any, any>) => any>`DELETE /app/installations/{installation_id}`

export type DeleteInstallationsByInstallationId = Api<typeof deleteInstallationsByInstallationId>

/**
 * Create an installation access token for an app
Creates an installation access token that enables a GitHub App to make authenticated API requests for the app's installation on an organization or individual account. Installation tokens expire one hour from the time you create them. Using an expired token produces a status code of `401 - Unauthorized`, and requires creating a new installation token. By default the installation token has access to all repositories that the installation can access. To restrict the access to specific repositories, you can provide the `repository_ids` when creating the token. When you omit `repository_ids`, the response does not contain the `repositories` key.

You must use a [JWT](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 */
export const postInstallationsByInstallationIdAccessTokens = api<(paths?: number, body?: UnnamedModel$2, config?: Config<any, UnnamedModel$2>) => any>`POST /app/installations/{installation_id}/access_tokens`

export type PostInstallationsByInstallationIdAccessTokens = Api<typeof postInstallationsByInstallationIdAccessTokens>

/**
 * Suspend an app installation
Suspends a GitHub App on a user, organization, or business account, which blocks the app from accessing the account's resources. When a GitHub App is suspended, the app's access to the GitHub Enterprise Server API or webhook events is blocked for that account.

You must use a [JWT](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 */
export const putInstallationsByInstallationIdSuspended = api<(paths?: number, config?: Config<any, any>) => any>`PUT /app/installations/{installation_id}/suspended`

export type PutInstallationsByInstallationIdSuspended = Api<typeof putInstallationsByInstallationIdSuspended>

/**
 * Unsuspend an app installation
Removes a GitHub App installation suspension.

You must use a [JWT](https://docs.github.com/enterprise-server@3.0/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) to access this endpoint.
 */
export const deleteInstallationsByInstallationIdSuspended = api<(paths?: number, config?: Config<any, any>) => any>`DELETE /app/installations/{installation_id}/suspended`

export type DeleteInstallationsByInstallationIdSuspended = Api<typeof deleteInstallationsByInstallationIdSuspended>
