/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */
import { api, type Config, type Api } from 'autoapi'
import {
  Code_of_conduct
} from './models/codes_of_conduct.d'

/**
 * Get all codes of conduct
 */
export const get = api<(config?: Config<any, any>) => Code_of_conduct[]>`GET /codes_of_conduct`

export type Get = Api<typeof get>

/**
 * Get a code of conduct
 */
export const getByKey = api<(paths?: string, config?: Config<any, any>) => any>`GET /codes_of_conduct/{key}`

export type GetByKey = Api<typeof getByKey>
