/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */
import { api, type Config, type Api } from 'ts-autoapi'

/**
 * Get emojis
Lists all the emojis available to use on GitHub Enterprise Server.
 */
export const get = api<(config?: Config<any, any>) => Record<string, any>>`GET /emojis`

export type Get = Api<typeof get>
