/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */
import { api, type Config, type Api } from 'autoapi'
import {
  Actions_enterprise_permissions,
  UnnamedModel,
  GetByEnterpriseActionsPermissionsOrganizationsQuery,
  UnnamedModel$1,
  UnnamedModel$2,
  Selected_actions,
  GetByEnterpriseActionsRunnerGroupsQuery,
  UnnamedModel$3,
  UnnamedModel$4,
  UnnamedModel$5,
  GetByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizationsQuery,
  UnnamedModel$6,
  UnnamedModel$7,
  GetByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunnersQuery,
  Runner,
  UnnamedModel$8,
  UnnamedModel$9,
  GetByEnterpriseActionsRunnersQuery,
  UnnamedModel$10,
  Runner_application
} from './models/enterprises.d'

/**
 * Get GitHub Actions permissions for an enterprise
Gets the GitHub Actions permissions policy for organizations and allowed actions in an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsPermissions = api<(paths?: string, config?: Config<any, any>) => Actions_enterprise_permissions>`GET /enterprises/{enterprise}/actions/permissions`

export type GetByEnterpriseActionsPermissions = Api<typeof getByEnterpriseActionsPermissions>

/**
 * Set GitHub Actions permissions for an enterprise
Sets the GitHub Actions permissions policy for organizations and allowed actions in an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const putByEnterpriseActionsPermissions = api<(paths?: string, body?: UnnamedModel, config?: Config<any, UnnamedModel>) => any>`PUT /enterprises/{enterprise}/actions/permissions`

export type PutByEnterpriseActionsPermissions = Api<typeof putByEnterpriseActionsPermissions>

/**
 * List selected organizations enabled for GitHub Actions in an enterprise
Lists the organizations that are selected to have GitHub Actions enabled in an enterprise. To use this endpoint, the enterprise permission policy for `enabled_organizations` must be configured to `selected`. For more information, see "[Set GitHub Actions permissions for an enterprise](#set-github-actions-permissions-for-an-enterprise)."

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsPermissionsOrganizations = api<(paths?: string, query?: GetByEnterpriseActionsPermissionsOrganizationsQuery, config?: Config<GetByEnterpriseActionsPermissionsOrganizationsQuery, any>) => UnnamedModel$1>`GET /enterprises/{enterprise}/actions/permissions/organizations`

export type GetByEnterpriseActionsPermissionsOrganizations = Api<typeof getByEnterpriseActionsPermissionsOrganizations>

/**
 * Set selected organizations enabled for GitHub Actions in an enterprise
Replaces the list of selected organizations that are enabled for GitHub Actions in an enterprise. To use this endpoint, the enterprise permission policy for `enabled_organizations` must be configured to `selected`. For more information, see "[Set GitHub Actions permissions for an enterprise](#set-github-actions-permissions-for-an-enterprise)."

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const putByEnterpriseActionsPermissionsOrganizations = api<(paths?: string, body?: UnnamedModel$2, config?: Config<any, UnnamedModel$2>) => any>`PUT /enterprises/{enterprise}/actions/permissions/organizations`

export type PutByEnterpriseActionsPermissionsOrganizations = Api<typeof putByEnterpriseActionsPermissionsOrganizations>

/**
 * Enable a selected organization for GitHub Actions in an enterprise
Adds an organization to the list of selected organizations that are enabled for GitHub Actions in an enterprise. To use this endpoint, the enterprise permission policy for `enabled_organizations` must be configured to `selected`. For more information, see "[Set GitHub Actions permissions for an enterprise](#set-github-actions-permissions-for-an-enterprise)."

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const putByEnterpriseActionsPermissionsOrganizationsAndOrgId = api<(paths?: [enterprise: string, orgid: number], config?: Config<any, any>) => any>`PUT /enterprises/{enterprise}/actions/permissions/organizations/{org_id}`

export type PutByEnterpriseActionsPermissionsOrganizationsAndOrgId = Api<typeof putByEnterpriseActionsPermissionsOrganizationsAndOrgId>

/**
 * Disable a selected organization for GitHub Actions in an enterprise
Removes an organization from the list of selected organizations that are enabled for GitHub Actions in an enterprise. To use this endpoint, the enterprise permission policy for `enabled_organizations` must be configured to `selected`. For more information, see "[Set GitHub Actions permissions for an enterprise](#set-github-actions-permissions-for-an-enterprise)."

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const deleteByEnterpriseActionsPermissionsOrganizationsAndOrgId = api<(paths?: [enterprise: string, orgid: number], config?: Config<any, any>) => any>`DELETE /enterprises/{enterprise}/actions/permissions/organizations/{org_id}`

export type DeleteByEnterpriseActionsPermissionsOrganizationsAndOrgId = Api<typeof deleteByEnterpriseActionsPermissionsOrganizationsAndOrgId>

/**
 * Get allowed actions for an enterprise
Gets the selected actions that are allowed in an enterprise. To use this endpoint, the enterprise permission policy for `allowed_actions` must be configured to `selected`. For more information, see "[Set GitHub Actions permissions for an enterprise](#set-github-actions-permissions-for-an-enterprise)."

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsPermissionsSelectedActions = api<(paths?: string, config?: Config<any, any>) => Selected_actions>`GET /enterprises/{enterprise}/actions/permissions/selected-actions`

export type GetByEnterpriseActionsPermissionsSelectedActions = Api<typeof getByEnterpriseActionsPermissionsSelectedActions>

/**
 * Set allowed actions for an enterprise
Sets the actions that are allowed in an enterprise. To use this endpoint, the enterprise permission policy for `allowed_actions` must be configured to `selected`. For more information, see "[Set GitHub Actions permissions for an enterprise](#set-github-actions-permissions-for-an-enterprise)."

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const putByEnterpriseActionsPermissionsSelectedActions = api<(paths?: string, body?: any, config?: Config<any, any>) => any>`PUT /enterprises/{enterprise}/actions/permissions/selected-actions`

export type PutByEnterpriseActionsPermissionsSelectedActions = Api<typeof putByEnterpriseActionsPermissionsSelectedActions>

/**
 * List self-hosted runner groups for an enterprise
Lists all self-hosted runner groups for an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsRunnerGroups = api<(paths?: string, query?: GetByEnterpriseActionsRunnerGroupsQuery, config?: Config<GetByEnterpriseActionsRunnerGroupsQuery, any>) => UnnamedModel$3>`GET /enterprises/{enterprise}/actions/runner-groups`

export type GetByEnterpriseActionsRunnerGroups = Api<typeof getByEnterpriseActionsRunnerGroups>

/**
 * Create a self-hosted runner group for an enterprise
Creates a new self-hosted runner group for an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const postByEnterpriseActionsRunnerGroups = api<(paths?: string, body?: UnnamedModel$4, config?: Config<any, UnnamedModel$4>) => any>`POST /enterprises/{enterprise}/actions/runner-groups`

export type PostByEnterpriseActionsRunnerGroups = Api<typeof postByEnterpriseActionsRunnerGroups>

/**
 * Get a self-hosted runner group for an enterprise
Gets a specific self-hosted runner group for an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsRunnerGroupsAndRunnerGroupId = api<(paths?: [enterprise: string, runnergroupid: number], config?: Config<any, any>) => any>`GET /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}`

export type GetByEnterpriseActionsRunnerGroupsAndRunnerGroupId = Api<typeof getByEnterpriseActionsRunnerGroupsAndRunnerGroupId>

/**
 * Update a self-hosted runner group for an enterprise
Updates the `name` and `visibility` of a self-hosted runner group in an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const patchByEnterpriseActionsRunnerGroupsAndRunnerGroupId = api<(paths?: [enterprise: string, runnergroupid: number], body?: UnnamedModel$5, config?: Config<any, UnnamedModel$5>) => any>`PATCH /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}`

export type PatchByEnterpriseActionsRunnerGroupsAndRunnerGroupId = Api<typeof patchByEnterpriseActionsRunnerGroupsAndRunnerGroupId>

/**
 * Delete a self-hosted runner group from an enterprise
Deletes a self-hosted runner group for an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const deleteByEnterpriseActionsRunnerGroupsAndRunnerGroupId = api<(paths?: [enterprise: string, runnergroupid: number], config?: Config<any, any>) => any>`DELETE /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}`

export type DeleteByEnterpriseActionsRunnerGroupsAndRunnerGroupId = Api<typeof deleteByEnterpriseActionsRunnerGroupsAndRunnerGroupId>

/**
 * List organization access to a self-hosted runner group in an enterprise
Lists the organizations with access to a self-hosted runner group.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizations = api<(paths?: [enterprise: string, runnergroupid: number], query?: GetByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizationsQuery, config?: Config<GetByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizationsQuery, any>) => UnnamedModel$6>`GET /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations`

export type GetByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizations = Api<typeof getByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizations>

/**
 * Set organization access for a self-hosted runner group in an enterprise
Replaces the list of organizations that have access to a self-hosted runner configured in an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const putByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizations = api<(paths?: [enterprise: string, runnergroupid: number], body?: UnnamedModel$7, config?: Config<any, UnnamedModel$7>) => any>`PUT /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations`

export type PutByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizations = Api<typeof putByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizations>

/**
 * Add organization access to a self-hosted runner group in an enterprise
Adds an organization to the list of selected organizations that can access a self-hosted runner group. The runner group must have `visibility` set to `selected`. For more information, see "[Create a self-hosted runner group for an enterprise](#create-a-self-hosted-runner-group-for-an-enterprise)."

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const putByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizationsAndOrgId = api<(paths?: [enterprise: string, runnergroupid: number, orgid: number], config?: Config<any, any>) => any>`PUT /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations/{org_id}`

export type PutByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizationsAndOrgId = Api<typeof putByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizationsAndOrgId>

/**
 * Remove organization access to a self-hosted runner group in an enterprise
Removes an organization from the list of selected organizations that can access a self-hosted runner group. The runner group must have `visibility` set to `selected`. For more information, see "[Create a self-hosted runner group for an enterprise](#create-a-self-hosted-runner-group-for-an-enterprise)."

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const deleteByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizationsAndOrgId = api<(paths?: [enterprise: string, runnergroupid: number, orgid: number], config?: Config<any, any>) => any>`DELETE /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/organizations/{org_id}`

export type DeleteByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizationsAndOrgId = Api<typeof deleteByEnterpriseActionsRunnerGroupsAndRunnerGroupIdOrganizationsAndOrgId>

/**
 * List self-hosted runners in a group for an enterprise
Lists the self-hosted runners that are in a specific enterprise group.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunners = api<(paths?: [enterprise: string, runnergroupid: number], query?: GetByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunnersQuery, config?: Config<GetByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunnersQuery, any>) => UnnamedModel$8>`GET /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/runners`

export type GetByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunners = Api<typeof getByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunners>

/**
 * Set self-hosted runners in a group for an enterprise
Replaces the list of self-hosted runners that are part of an enterprise runner group.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const putByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunners = api<(paths?: [enterprise: string, runnergroupid: number], body?: UnnamedModel$9, config?: Config<any, UnnamedModel$9>) => any>`PUT /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/runners`

export type PutByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunners = Api<typeof putByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunners>

/**
 * Add a self-hosted runner to a group for an enterprise
Adds a self-hosted runner to a runner group configured in an enterprise.

You must authenticate using an access token with the `admin:enterprise`
scope to use this endpoint.
 */
export const putByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunnersAndRunnerId = api<(paths?: [enterprise: string, runnergroupid: number, runnerid: number], config?: Config<any, any>) => any>`PUT /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/runners/{runner_id}`

export type PutByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunnersAndRunnerId = Api<typeof putByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunnersAndRunnerId>

/**
 * Remove a self-hosted runner from a group for an enterprise
Removes a self-hosted runner from a group configured in an enterprise. The runner is then returned to the default group.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const deleteByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunnersAndRunnerId = api<(paths?: [enterprise: string, runnergroupid: number, runnerid: number], config?: Config<any, any>) => any>`DELETE /enterprises/{enterprise}/actions/runner-groups/{runner_group_id}/runners/{runner_id}`

export type DeleteByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunnersAndRunnerId = Api<typeof deleteByEnterpriseActionsRunnerGroupsAndRunnerGroupIdRunnersAndRunnerId>

/**
 * List self-hosted runners for an enterprise
Lists all self-hosted runners configured for an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsRunners = api<(paths?: string, query?: GetByEnterpriseActionsRunnersQuery, config?: Config<GetByEnterpriseActionsRunnersQuery, any>) => UnnamedModel$10>`GET /enterprises/{enterprise}/actions/runners`

export type GetByEnterpriseActionsRunners = Api<typeof getByEnterpriseActionsRunners>

/**
 * List runner applications for an enterprise
Lists binaries for the runner application that you can download and run.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsRunnersDownloads = api<(paths?: string, config?: Config<any, any>) => Runner_application[]>`GET /enterprises/{enterprise}/actions/runners/downloads`

export type GetByEnterpriseActionsRunnersDownloads = Api<typeof getByEnterpriseActionsRunnersDownloads>

/**
 * Create a registration token for an enterprise
Returns a token that you can pass to the `config` script. The token expires after one hour.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.

#### Example using registration token

Configure your self-hosted runner, replacing `TOKEN` with the registration token provided by this endpoint.

```
./config.sh --url https://github.com/enterprises/octo-enterprise --token TOKEN
```
 */
export const postByEnterpriseActionsRunnersRegistrationToken = api<(paths?: string, config?: Config<any, any>) => any>`POST /enterprises/{enterprise}/actions/runners/registration-token`

export type PostByEnterpriseActionsRunnersRegistrationToken = Api<typeof postByEnterpriseActionsRunnersRegistrationToken>

/**
 * Create a remove token for an enterprise
Returns a token that you can pass to the `config` script to remove a self-hosted runner from an enterprise. The token expires after one hour.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.

#### Example using remove token

To remove your self-hosted runner from an enterprise, replace `TOKEN` with the remove token provided by this
endpoint.

```
./config.sh remove --token TOKEN
```
 */
export const postByEnterpriseActionsRunnersRemoveToken = api<(paths?: string, config?: Config<any, any>) => any>`POST /enterprises/{enterprise}/actions/runners/remove-token`

export type PostByEnterpriseActionsRunnersRemoveToken = Api<typeof postByEnterpriseActionsRunnersRemoveToken>

/**
 * Get a self-hosted runner for an enterprise
Gets a specific self-hosted runner configured in an enterprise.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const getByEnterpriseActionsRunnersAndRunnerId = api<(paths?: [enterprise: string, runnerid: number], config?: Config<any, any>) => any>`GET /enterprises/{enterprise}/actions/runners/{runner_id}`

export type GetByEnterpriseActionsRunnersAndRunnerId = Api<typeof getByEnterpriseActionsRunnersAndRunnerId>

/**
 * Delete a self-hosted runner from an enterprise
Forces the removal of a self-hosted runner from an enterprise. You can use this endpoint to completely remove the runner when the machine you were using no longer exists.

You must authenticate using an access token with the `admin:enterprise` scope to use this endpoint.
 */
export const deleteByEnterpriseActionsRunnersAndRunnerId = api<(paths?: [enterprise: string, runnerid: number], config?: Config<any, any>) => any>`DELETE /enterprises/{enterprise}/actions/runners/{runner_id}`

export type DeleteByEnterpriseActionsRunnersAndRunnerId = Api<typeof deleteByEnterpriseActionsRunnersAndRunnerId>
