/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */
import { api, type Config, type Api } from 'ts-autoapi'
import {
  GetQuery,
  Event
} from './models/events.d'

/**
 * List public events
We delay the public events feed by five minutes, which means the most recent event returned by the public events API actually occurred at least five minutes ago.
 */
export const get = api<(query?: GetQuery, config?: Config<GetQuery, any>) => Event[]>`GET /events`

export type Get = Api<typeof get>
