/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */
import { api, type Config, type Api } from 'ts-autoapi'
import {
  Gitignore_template
} from './models/gitignore.d'

/**
 * Get all gitignore templates
List all templates available to pass as an option when [creating a repository](https://docs.github.com/enterprise-server@3.0/rest/reference/repos#create-a-repository-for-the-authenticated-user).
 */
export const getTemplates = api<(config?: Config<any, any>) => string[]>`GET /gitignore/templates`

export type GetTemplates = Api<typeof getTemplates>

/**
 * Get a gitignore template
The API also allows fetching the source of a single template.
Use the raw [media type](https://docs.github.com/enterprise-server@3.0/rest/overview/media-types/) to get the raw contents.
 */
export const getTemplatesByName = api<(paths?: string, config?: Config<any, any>) => Gitignore_template>`GET /gitignore/templates/{name}`

export type GetTemplatesByName = Api<typeof getTemplatesByName>
