/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */
import { api, type Config, type Api } from 'autoapi'
import {
  GetQuery,
  License_simple,
  License
} from './models/licenses.d'

/**
 * Get all commonly used licenses
 */
export const get = api<(query?: GetQuery, config?: Config<GetQuery, any>) => License_simple[]>`GET /licenses`

export type Get = Api<typeof get>

/**
 * Get a license
 */
export const getByLicense = api<(paths?: string, config?: Config<any, any>) => License>`GET /licenses/{license}`

export type GetByLicense = Api<typeof getByLicense>
