/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */
import { api, type Config, type Api } from 'autoapi'
import {
  UnnamedModel
} from './models/markdown.d'

/**
 * Render a Markdown document
 */
export const post = api<(body?: UnnamedModel, config?: Config<any, UnnamedModel>) => any>`POST /markdown`

export type Post = Api<typeof post>

/**
 * Render a Markdown document in raw mode
You must send Markdown as plain text (using a `Content-Type` header of `text/plain` or `text/x-markdown`) to this endpoint, rather than using JSON format. In raw mode, [GitHub Flavored Markdown](https://github.github.com/gfm/) is not supported and Markdown will be rendered in plain format like a README.md file. Markdown content must be 400 KB or less.
 */
export const postRaw = api<(config?: Config<any, any>) => any>`POST /markdown/raw`

export type PostRaw = Api<typeof postRaw>
