/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */
import { api, type Config, type Api } from 'ts-autoapi'
import {
  Api_overview
} from './models/meta.d'

/**
 * Get GitHub Enterprise Server meta information
 */
export const get = api<(config?: Config<any, any>) => Api_overview>`GET /meta`

export type Get = Api<typeof get>
