/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */
import { api, type Config, type Api } from 'ts-autoapi'
import {
  GetByOwnerAndRepoEventsQuery
} from './models/networks.d'

/**
 * List public events for a network of repositories
 */
export const getByOwnerAndRepoEvents = api<(paths?: [owner: string, repo: string], query?: GetByOwnerAndRepoEventsQuery, config?: Config<GetByOwnerAndRepoEventsQuery, any>) => any[]>`GET /networks/{owner}/{repo}/events`

export type GetByOwnerAndRepoEvents = Api<typeof getByOwnerAndRepoEvents>
