/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */
import { api, type Config, type Api } from 'ts-autoapi'
import {
  GetQuery
} from './models/octocat.d'

/**
 * Get Octocat
Get the octocat as ASCII art
 */
export const get = api<(query?: GetQuery, config?: Config<GetQuery, any>) => any>`GET /octocat`

export type Get = Api<typeof get>
