/* eslint-disable */

/**
 * This file was auto generated by `ts-autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the ts-autoapi cli.
 */
import { api, type Config, type Api } from 'ts-autoapi'
import {
  Rate_limit,
  Rate_limit_overview
} from './models/rate_limit.d'

/**
 * Get rate limit status for the authenticated user
**Note:** Accessing this endpoint does not count against your REST API rate limit.

**Note:** The `rate` object is deprecated. If you're writing new API client code or updating existing code, you should use the `core` object instead of the `rate` object. The `core` object contains the same information that is present in the `rate` object.
 */
export const get = api<(config?: Config<any, any>) => Rate_limit_overview>`GET /rate_limit`

export type Get = Api<typeof get>
