/* eslint-disable */

/**
 * This file was auto generated by `autoapi`.
 * Do not make direct changes to the file.
 * If you need to make changes with openapi doc file,
 * please use the autoapi cli.
 */
import { api, type Config, type Api } from 'autoapi'

/**
 * Get the Zen of GitHub
Get a random sentence from the Zen of GitHub
 */
export const get = api<(config?: Config<any, any>) => any>`GET /zen`

export type Get = Api<typeof get>
